name: Create Release
on:
  issues:
    types: [opened]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Autoreply issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.issue.number}}
          body: |
            Thank you for using Homebridge TaHoma plugin.

            Please follow these step to obtain better support :
            1. Execute failling operations from official app (TaHoma/Cozytouch/etc.) then execute same operation from Homekit
            2. Report your config by browsing [https://dev.duboc.pro/tahoma](https://dev.duboc.pro/tahoma)
            3. Search issues with title corresponding to your device widget name (see picture below). If no opened issue, rename your issue with this widget name.
            4. Provide your bridge last 4 digits (number visible as SETUP-XXXX-XXXX-XXXX at step 2.)
            ![Widget](https://dev.duboc.pro/img/widgets.png)

            Thank you.
          token: ${{ secrets.GITHUB_TOKEN }}