name: Deploy NPM release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Setup GIT
        run: |
          git config --global user.email "dubocr@gmail.com"
          git config --global user.name ${{github.repository_owner}}
      - name: Install & Test
        run: |
          npm install
          npm run lint
      - name: Deploy
        run: |
          npm version patch --m 'Release %s' --force
          git add -A dist
          git push
          git push --tags
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}